Feature/validate wall
Chloekkk/cub3D pull request #7
Opened 2022-09-20 12:02 UTC by Kimhan-nah

## 개요 
#4 
## 작업내용 
* ' ' (공백) 기준 상하좌우에 ' '(공백) 또는 '1'(벽)만 존재해야 함
* 0번째 row : 하, 좌, 우 확인
* 마지막 row : 상, 좌, 우 확인
* 나머지 : 상, 하, 좌, 우 확인
## 주의사항 
* 각 line에서 0번째 column, 마지막 column은 또 다름!

2022-09-20 12:58 UTC, Chloekkk requested changes
전체 리베이스 받아서 수정해주세욤

2022-09-20 12:58 UTC, Chloekkk commented on Makefile
> +<<<<<<< HEAD
왓더퍽!!!!!ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-09-20 13:24 UTC, Chloekkk approved these changes

2022-09-21 10:08 UTC, Chloekkk approved these changes
LGTM

2022-09-21 10:08 UTC, nyeoni commented on include/cub3D.h
> +# define EAST 'E'
direction 은 `t_dir` 에 있는 enum 들을 이용하시면 더 좋을 것 같습니다 :-)

2022-09-21 10:08 UTC, merged